import { Badge } from "../types";

export const ALL_BADGES: Badge[] = [
  // === COLLECTION (Chats) ===
  {
    id: "badge_first_cat",
    name: "Premier chat",
    description: "Tu as répertorié ton premier chat",
    icon: "🐱",
    criteria: "first_cat",
    tier: "bronze",
    progressTarget: 1,
    criteriaType: "collection",
  },
  {
    id: "badge_five_cats",
    name: "Collectionneur",
    description: "5 chats dans ta collection",
    icon: "🐾",
    criteria: "five_cats",
    tier: "bronze",
    progressTarget: 5,
    criteriaType: "collection",
  },
  {
    id: "badge_ten_cats",
    name: "10 chats",
    description: "10 chats dans ta collection",
    icon: "🐈",
    criteria: "ten_cats",
    tier: "silver",
    progressTarget: 10,
    criteriaType: "collection",
  },
  {
    id: "badge_twentyfive_cats",
    name: "Expert félin",
    description: "25 chats répertoriés !",
    icon: "🐈‍⬛",
    criteria: "twentyfive_cats",
    tier: "silver",
    progressTarget: 25,
    criteriaType: "collection",
  },
  {
    id: "badge_fifty_cats",
    name: "Crazy Cat Lady",
    description: "50 chats ! Tu es un maître des chats",
    icon: "🏆",
    criteria: "fifty_cats",
    tier: "gold",
    progressTarget: 50,
    criteriaType: "collection",
  },
  {
    id: "badge_hundred_cats",
    name: "Légende féline",
    description: "100 chats ! Un vrai répertoire",
    icon: "👑",
    criteria: "hundred_cats",
    tier: "platinum",
    progressTarget: 100,
    criteriaType: "collection",
  },

  // === FAVORIS ===
  {
    id: "badge_first_favorite",
    name: "Premier favori",
    description: "Tu as ajouté un chat en favori",
    icon: "❤️",
    criteria: "first_favorite",
    tier: "bronze",
    progressTarget: 1,
    criteriaType: "favorites",
  },
  {
    id: "badge_five_favorites",
    name: "Fan de chats",
    description: "5 chats en favoris",
    icon: "💕",
    criteria: "five_favorites",
    tier: "bronze",
    progressTarget: 5,
    criteriaType: "favorites",
  },
  {
    id: "badge_ten_favorites",
    name: "Mon cœur bat",
    description: "10 chats adorés",
    icon: "💖",
    criteria: "ten_favorites",
    tier: "silver",
    progressTarget: 10,
    criteriaType: "favorites",
  },
  {
    id: "badge_twentyfive_favorites",
    name: "Amour inconditionnel",
    description: "25 chats favoris",
    icon: "💗",
    criteria: "twentyfive_favorites",
    tier: "gold",
    progressTarget: 25,
    criteriaType: "favorites",
  },
  {
    id: "badge_fifty_favorites",
    name: "Polyamour félin",
    description: "50 chats dans ton cœur",
    icon: "💘",
    criteria: "fifty_favorites",
    tier: "platinum",
    progressTarget: 50,
    criteriaType: "favorites",
  },

  // === OBSERVATIONS ===
  {
    id: "badge_first_sighting",
    name: "Première observation",
    description: "Tu as observé un chat à proximité",
    icon: "👀",
    criteria: "first_sighting",
    tier: "bronze",
    progressTarget: 1,
    criteriaType: "sightings",
  },
  {
    id: "badge_ten_sightings",
    name: "10 observations",
    description: "10 observations enregistrées",
    icon: "📸",
    criteria: "ten_sightings",
    tier: "bronze",
    progressTarget: 10,
    criteriaType: "sightings",
  },
  {
    id: "badge_twentyfive_sightings",
    name: "Paparazzi",
    description: "25 observations réalisées",
    icon: "📷",
    criteria: "twentyfive_sightings",
    tier: "silver",
    progressTarget: 25,
    criteriaType: "sightings",
  },
  {
    id: "badge_fifty_sightings",
    name: "Enquêteur",
    description: "50 observations enregistrées",
    icon: "🔍",
    criteria: "fifty_sightings",
    tier: "gold",
    progressTarget: 50,
    criteriaType: "sightings",
  },
  {
    id: "badge_hundred_sightings",
    name: "Espion félin",
    description: "100 observations ! Ton œil est affûté",
    icon: "🕵️",
    criteria: "hundred_sightings",
    tier: "gold",
    progressTarget: 100,
    criteriaType: "sightings",
  },
  {
    id: "badge_fivehundred_sightings",
    name: "Oeil de faucon",
    description: "500 observations ! Un vrai professionnel",
    icon: "🦅",
    criteria: "fivehundred_sightings",
    tier: "platinum",
    progressTarget: 500,
    criteriaType: "sightings",
  },

  // === PHOTOS ===
  {
    id: "badge_first_photo",
    name: "Photographe",
    description: "Première photo prise",
    icon: "📱",
    criteria: "first_photo",
    tier: "bronze",
    progressTarget: 1,
    criteriaType: "photos",
  },
  {
    id: "badge_ten_photos",
    name: "Photo reporter",
    description: "10 photos prises",
    icon: "🤳",
    criteria: "ten_photos",
    tier: "silver",
    progressTarget: 10,
    criteriaType: "photos",
  },
  {
    id: "badge_fifty_photos",
    name: "Artiste",
    description: "50 photos ! Ta galerie est impressionnante",
    icon: "🖼️",
    criteria: "fifty_photos",
    tier: "gold",
    progressTarget: 50,
    criteriaType: "photos",
  },

  // === COULEURS ===
  {
    id: "badge_orange_cat",
    name: "Chat roux",
    description: "Tu as croisé un chat roux",
    icon: "🦁",
    criteria: "cat_color_roux",
    tier: "bronze",
    progressTarget: 1,
    criteriaType: "color",
  },
  {
    id: "badge_black_cat",
    name: "Chat noir",
    description: "Tu as croisé un chat noir",
    icon: "🐈‍⬛",
    criteria: "cat_color_noir",
    tier: "bronze",
    progressTarget: 1,
    criteriaType: "color",
  },
  {
    id: "badge_white_cat",
    name: "Chat blanc",
    description: "Tu as croisé un chat blanc",
    icon: "🐇",
    criteria: "cat_color_blanc",
    tier: "bronze",
    progressTarget: 1,
    criteriaType: "color",
  },
  {
    id: "badge_grey_cat",
    name: "Chat gris",
    description: "Tu as croisé un chat gris",
    icon: "🐭",
    criteria: "cat_color_gris",
    tier: "bronze",
    progressTarget: 1,
    criteriaType: "color",
  },
  {
    id: "badge_tabby_cat",
    name: "Chat tigré",
    description: "Tu as croisé un chat tigré",
    icon: "🐅",
    criteria: "cat_color_tigré",
    tier: "bronze",
    progressTarget: 1,
    criteriaType: "color",
  },
  {
    id: "badge_tricolor_cat",
    name: "Chat tricolore",
    description: "Tu as croisé un chat tricolore",
    icon: "🎨",
    criteria: "cat_color_tricolore",
    tier: "bronze",
    progressTarget: 1,
    criteriaType: "color",
  },
  {
    id: "badge_siamese_cat",
    name: "Chat siamois",
    description: "Tu as croisé un chat siamois",
    icon: "🇹🇭",
    criteria: "cat_color_siamois",
    tier: "silver",
    progressTarget: 1,
    criteriaType: "color",
  },

  // === VILLES ===
  {
    id: "badge_first_city",
    name: "Voyageur",
    description: "1 ville visitée",
    icon: "🏙️",
    criteria: "first_city",
    tier: "bronze",
    progressTarget: 1,
    criteriaType: "cities",
  },
  {
    id: "badge_five_cities",
    name: "Globe-trotter",
    description: "5 villes différentes explorées",
    icon: "🌆",
    criteria: "five_cities",
    tier: "silver",
    progressTarget: 5,
    criteriaType: "cities",
  },
  {
    id: "badge_ten_cities",
    name: "Citoyen du monde",
    description: "10 villes visitées !",
    icon: "🗺️",
    criteria: "ten_cities",
    tier: "gold",
    progressTarget: 10,
    criteriaType: "cities",
  },
  {
    id: "badge_twentyfive_cities",
    name: "Explorateur",
    description: "25 villes explorées !",
    icon: "🌍",
    criteria: "twentyfive_cities",
    tier: "platinum",
    progressTarget: 25,
    criteriaType: "cities",
  },

  // === STREAKS (Jours consécutifs) ===
  {
    id: "badge_streak_3",
    name: "Sur la bonne voie",
    description: "3 jours d'affilée sur l'app",
    icon: "🔥",
    criteria: "streak_3",
    tier: "bronze",
    progressTarget: 3,
    criteriaType: "streak",
  },
  {
    id: "badge_streak_7",
    name: "Semaine parfaite",
    description: "7 jours d'affilée ! Un vrai habitué",
    icon: "🗓️",
    criteria: "streak_7",
    tier: "silver",
    progressTarget: 7,
    criteriaType: "streak",
  },
  {
    id: "badge_streak_14",
    name: "Deux semaines",
    description: "14 jours consécutifs d'activité",
    icon: "📅",
    criteria: "streak_14",
    tier: "gold",
    progressTarget: 14,
    criteriaType: "streak",
  },
  {
    id: "badge_streak_30",
    name: "Mois complet",
    description: "30 jours d'affilée ! Dévotion totale",
    icon: "🌙",
    criteria: "streak_30",
    tier: "gold",
    progressTarget: 30,
    criteriaType: "streak",
  },
  {
    id: "badge_streak_100",
    name: "Cent jours de passion",
    description: "100 jours consécutifs ! Légendes",
    icon: "💯",
    criteria: "streak_100",
    tier: "platinum",
    progressTarget: 100,
    criteriaType: "streak",
  },

  // === BADGES CACHÉS ===
  {
    id: "badge_midnight_cat",
    name: "Chasseur de minuit",
    description: "Observé un chat à minuit",
    icon: "🌙",
    criteria: "midnight_cat",
    tier: "secret",
    hidden: true,
    progressTarget: 1,
    criteriaType: "hidden",
  },
  {
    id: "badge_speed_runner",
    name: "Speed runner",
    description: "5 chats ajoutés en 1 heure",
    icon: "⚡",
    criteria: "speed_runner",
    tier: "secret",
    hidden: true,
    progressTarget: 1,
    criteriaType: "hidden",
  },
  {
    id: "badge_lucky_cat",
    name: "Chat porte-bonheur",
    description: "Ajouté ton 7ème chat",
    icon: "🍀",
    criteria: "lucky_seven",
    tier: "secret",
    hidden: true,
    progressTarget: 1,
    criteriaType: "hidden",
  },
  {
    id: "badge_paparazzi_rain",
    name: "Sous la pluie",
    description: "Photo prise sous la pluie",
    icon: "🌧️",
    criteria: "rain_photo",
    tier: "secret",
    hidden: true,
    progressTarget: 1,
    criteriaType: "hidden",
  },
  {
    id: "badge_ghost_hunter",
    name: "Chasseur de fantômes",
    description: "A trouvé un chat caché",
    icon: "👻",
    criteria: "ghost_cat",
    tier: "secret",
    hidden: true,
    progressTarget: 1,
    criteriaType: "hidden",
  },
  {
    id: "badge_collector_perfect",
    name: "Collection parfaite",
    description: "Toutes les couleurs découvertes",
    icon: "🌈",
    criteria: "all_colors",
    tier: "secret",
    hidden: true,
    progressTarget: 1,
    criteriaType: "hidden",
  },
  {
    id: "badge_first_breed",
    name: "Répertorié une race",
    description: "Tu as enregistré une race de chat",
    icon: "🏅",
    criteria: "first_breed",
    tier: "bronze",
    progressTarget: 1,
    criteriaType: "collection",
  },
  {
    id: "badge_five_breeds",
    name: "Connaisseur",
    description: "5 races différentes répertoriées",
    icon: "📚",
    criteria: "five_breeds",
    tier: "silver",
    progressTarget: 5,
    criteriaType: "collection",
  },
  {
    id: "badge_ten_breeds",
    name: "Expert en races",
    description: "10 races de chats connues",
    icon: "🎓",
    criteria: "ten_breeds",
    tier: "gold",
    progressTarget: 10,
    criteriaType: "collection",
  },
  {
    id: "badge_socialite",
    name: "Socialité",
    description: "Enregistré un chat sociable",
    icon: "🤝",
    criteria: "social_cat",
    tier: "bronze",
    progressTarget: 1,
    criteriaType: "collection",
  },
  {
    id: "badge_shy_cat",
    name: "Timide",
    description: "Enregistré un chat craintif",
    icon: "😾",
    criteria: "shy_cat",
    tier: "bronze",
    progressTarget: 1,
    criteriaType: "collection",
  },
  {
    id: "badge_night_owl",
    name: "Couche-tard",
    description: "Ajouté un chat après 22h",
    icon: "🦉",
    criteria: "night_owl",
    tier: "silver",
    hidden: true,
    progressTarget: 1,
    criteriaType: "hidden",
  },
  {
    id: "badge_early_bird",
    name: "Lève-tôt",
    description: "Ajouté un chat avant 7h",
    icon: "🌅",
    criteria: "early_bird",
    tier: "silver",
    hidden: true,
    progressTarget: 1,
    criteriaType: "hidden",
  },
  {
    id: "badge_weekend_warrior",
    name: "Week-end warrior",
    description: "Actif pendant le week-end",
    icon: "🎉",
    criteria: "weekend_warrior",
    tier: "silver",
    hidden: true,
    progressTarget: 1,
    criteriaType: "hidden",
  },

  // === OBSERVATIONS STREAK ===
  {
    id: "badge_sighting_streak_3",
    name: "Œil vif",
    description: "3 jours d'observations consécutives",
    icon: "👁️",
    criteria: "sighting_streak_3",
    tier: "bronze",
    progressTarget: 3,
    criteriaType: "streak",
  },
];
